//---------------------------------------------------------------------------
//
//	X68000 EMULATOR "XM6"
//
//	Copyright (C) 2001-2004 PI (ytanaka@ipc-tokai.or.jp)
//	Modified (C) 2006 co (cogood@gmail.com)
//	[ Windrv ]
//
//---------------------------------------------------------------------------

#include <windows.h>
#include "os.h"
#include "xm6.h"
#include "vm.h"
#include "log.h"
#include "schedule.h"
#include "memory.h"
#include "cpu.h"
#include "config.h"
#include "windrv.h"

//===========================================================================
//
//	Human68k
//
//===========================================================================

//---------------------------------------------------------------------------
//
//	Destructor
//
//---------------------------------------------------------------------------
void FASTCALL Human68k::namests_t::GetCopyPath(BYTE* szPath) const
{
	ASSERT(this);
	ASSERT(szPath);
	// WARNING: Unicode not supported

	BYTE* p = szPath;
	for (int i = 0; i < 65; i++) {
		BYTE c = path[i];
		if (c == '\0') break;
		if (c == 0x09) {
			c = '/';
		}
		*p++ = c;
	}

	*p = '\0';
}

//---------------------------------------------------------------------------
//
//	Get filename
//
//	Provides file search capability for entries generated by TwentyOne.
//
//	Directory entry function disabled:
//	In Human68k, wildcard strings are replaced with '?'
//	る18 + 3文字以上の長いファイル名の検索が不可能这样的话
//	This is because the file kernel string conversion allows all files
//	to be searched, and this is highly recommended
//	
//
//	When all files are opened, the directory entry is
//	released and temporarily stopped.
//
//---------------------------------------------------------------------------
void FASTCALL Human68k::namests_t::GetCopyFilename(BYTE* szFilename) const
{
	ASSERT(this);
	ASSERT(szFilename);
	// WARNING: Unicode not supported

	int i;
	BYTE* p = szFilename;
#ifdef XM6_WINDRV_WILDCARD
	BYTE* pWild = NULL;
#endif // XM6_WINDRV_WILDCARD

	// Copy filename part
	for (i = 0; i < 8; i++) {
		BYTE c = name[i];
		if (c == ' ') {
			BOOL bTerminate = TRUE;
			// 繝輔ぃ繧､繝ｫ蜷堺ｸｭ縺ｫ繧ｹ繝壹ｼ繧ｹ縺悟ｺ迴ｾ縺励◆蝣ｴ蜷医∽ｻ･髯阪ｮ繧ｨ繝ｳ繝医Μ縺檎ｶ壹＞縺ｦ縺繧九°縺ｩ縺縺狗｢ｺ隱
			// If add[0] is not empty, it is a valid entry
			if (add[0] != '\0') {
				bTerminate = FALSE;
			} else {
				// Check if there is any non-space character after name[i]
				for (int j = i + 1; j < 8; j++) {
					if (name[j] != ' ') {
						bTerminate = FALSE;
						break;
					}
				}
			}
			// Terminate filename copy if needed
			if (bTerminate) break;
		}
#ifdef XM6_WINDRV_WILDCARD
		if (c == '?') {
			if (pWild == NULL) pWild = p;
		} else {
			pWild = NULL;
		}
#endif // XM6_WINDRV_WILDCARD
		*p++ = c;
}
	// All characters read, now i >= 8

	// If filename part is full (8 chars), also copy extension part
	if (i >= 8) {
		// Copy extension part
		for (i = 0; i < 10; i++) {
			BYTE c = add[i];
			if (c == '\0') break;
#ifdef XM6_WINDRV_WILDCARD
			if (c == '?') {
				if (pWild == NULL) pWild = p;
			} else {
				pWild = NULL;
			}
#endif // XM6_WINDRV_WILDCARD
			*p++ = c;
}
		// All characters read, now i >= 10
	}

#ifdef XM6_WINDRV_WILDCARD
	// 繝輔ぃ繧､繝ｫ蜷肴忰蟆ｾ縺後Ρ繧､繝ｫ繝峨き繝ｼ繝峨〒縲√°縺､蠕悟濠10譁蟄励ｮ縺吶∋縺ｦ繧剃ｽｿ逕ｨ縺励※縺繧九°ｼ
	if (pWild && i >= 10) {
		p = pWild;
		*p++ = '*';
	}
#endif // XM6_WINDRV_WILDCARD

	// Filename part is complete, process extension
#ifdef XM6_WINDRV_WILDCARD
	pWild = NULL;
#endif // XM6_WINDRV_WILDCARD
	i = 0;

	// Does extension exist?
	if (ext[0] == ' ' && ext[1] == ' ' && ext[2] == ' ') {
		// No extension
	} else {
		// Copy extension
		*p++ = '.';
		for (i = 0; i < 3; i++) {
			BYTE c = ext[i];
			if (c == ' ') {
				BOOL bTerminate = TRUE;
				// Check if space appears in middle of extension (entry has extension)
				// Check if there is any non-space character after ext[i]
				for (int j = i + 1; j < 3; j++) {
					if (ext[j] != ' ') {
						bTerminate = FALSE;
						break;
					}
				}
				// Terminate extension copy if needed
				if (bTerminate) break;
			}
#ifdef XM6_WINDRV_WILDCARD
			if (c == '?') {
				if (pWild == NULL) pWild = p;
			} else {
				pWild = NULL;
			}
#endif // XM6_WINDRV_WILDCARD
			*p++ = c;
}
		// All characters read, now i >= 3
	}

#ifdef XM6_WINDRV_WILDCARD
	// If wildcard in extension, use first 3 chars only
	if (pWild && i >= 3) {
		p = pWild;
		*p++ = '*';
	}
#endif // XM6_WINDRV_WILDCARD

	// Return path
	*p = '\0';
}

//===========================================================================
//
//	Command handler
//
//===========================================================================

//---------------------------------------------------------------------------
//
//	繧ｳ繝ｳ繧ｹ繝医Λ繧ｯ繧ｿ
//
//---------------------------------------------------------------------------
CWindrv::CWindrv(Windrv* pWindrv, Memory* pMemory, DWORD nHandle)
{
	windrv = pWindrv;
	memory = pMemory;
	a5 = 0;
	unit = 0;
	command = 0;

	m_nHandle = nHandle;
	m_bAlloc = FALSE;
	m_bExecute = FALSE;
	m_bReady = FALSE;
	m_bTerminate = FALSE;
	m_hThread = NULL;
	m_hEventStart = NULL;
	m_hEventReady = NULL;
}

//---------------------------------------------------------------------------
//
//	Constructor
//
//---------------------------------------------------------------------------
CWindrv::~CWindrv()
{
	Terminate();
}

//---------------------------------------------------------------------------
//
//	Thread start
//
//---------------------------------------------------------------------------
BOOL FASTCALL CWindrv::Start()
{
	ASSERT(this);
	ASSERT(m_bAlloc == FALSE);
	ASSERT(m_bExecute == FALSE);
	ASSERT(m_bTerminate == FALSE);
	ASSERT(m_hThread == NULL);
	ASSERT(m_hEventStart == NULL);
	ASSERT(m_hEventReady == NULL);

	// Event handle
	m_hEventStart = ::CreateEvent(NULL, FALSE, FALSE, NULL);	// 閾ｪ蜍輔Μ繧ｻ繝繝
	ASSERT(m_hEventStart);

	m_hEventReady = ::CreateEvent(NULL, TRUE, FALSE, NULL);	// Auto繝ｪ繧ｻ繝繝 pending
	ASSERT(m_hEventReady);

	// 繧ｹ繝ｬ繝繝臥函謌
	DWORD nThread;
	m_hThread = ::CreateThread(NULL, 0, Run, this, 0, &nThread);
	ASSERT(m_hThread);

	// Error繝√ぉ繝繧ｯ
	if (m_hEventStart == NULL ||
		m_hEventReady == NULL ||
		m_hThread == NULL) return FALSE;

	return TRUE;
}

//---------------------------------------------------------------------------
//
//	繧ｹ繝ｬ繝繝牙●豁｢
//
//---------------------------------------------------------------------------
BOOL FASTCALL CWindrv::Terminate()
{
	ASSERT(this);

	BOOL bResult = TRUE;

	if (m_hThread) {
		ASSERT(m_bTerminate == FALSE);
		ASSERT(m_hEventStart);

		// 繧ｹ繝ｬ繝繝峨∈蛛懈ｭ｢隕∵ｱ
		m_bTerminate = TRUE;
		::SetEvent(m_hEventStart);

		// 繧ｹ繝ｬ繝繝臥ｵゆｺ蠕縺｡
		DWORD nResult;
		nResult = ::WaitForSingleObject(m_hThread, 30 * 1000);	// 迪ｶ莠域悄髢 30遘
		if (nResult != WAIT_OBJECT_0) {
			// 蠑ｷ蛻ｶ蛛懈ｭ｢
			ASSERT(FALSE);	// 蠢ｵ縺ｮ縺溘ａ
			::TerminateThread(m_hThread, (DWORD)-1);
			nResult = ::WaitForSingleObject(m_hThread, 100);
			bResult = FALSE;
		}

		// 繧ｹ繝ｬ繝繝峨ワ繝ｳ繝峨Νrelease
		::CloseHandle(m_hThread);
		m_hThread = NULL;

		// 蛛懈ｭ｢隕∵ｱゅｒ蜿悶ｊ荳九￡繧
		m_bTerminate = FALSE;
	}

	// 繧､繝吶Φ繝医ワ繝ｳ繝峨Νrelease
	if (m_hEventStart) {
		::CloseHandle(m_hEventStart);
		m_hEventStart = NULL;
	}

	if (m_hEventReady) {
		::CloseHandle(m_hEventReady);
		m_hEventReady = NULL;
	}

	// 縺昴ｮ縺ｾ縺ｾ蜷後§繧ｪ繝悶ず繧ｧ繧ｯ繝医〒繧ｹ繝ｬ繝繝芽ｵｷ蜍輔〒縺阪ｋ繧医≧Initialize
	m_bAlloc = FALSE;
	m_bExecute = FALSE;
	m_bReady = FALSE;
	m_bTerminate = FALSE;

	return bResult;
}

//---------------------------------------------------------------------------
//
//	Command execute
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Execute(DWORD nA5)
{
	ASSERT(this);
	ASSERT(m_bExecute == FALSE);
	ASSERT(m_bTerminate == FALSE);
	ASSERT(m_hThread);
	ASSERT(m_hEventStart);
	ASSERT(m_hEventReady);
	ASSERT(nA5 <= 0xFFFFFF);

	// Execute碁幕蟋九ヵ繝ｩ繧ｰ繧ｻ繝繝
	m_bExecute = TRUE;

	// 繝ｪ繧ｯ繧ｨ繧ｹ繝医倥ャ繝縺ｮ繧｢繝峨Ξ繧ｹ
	a5 = nA5;

	// Error諠蝣ｱ繧偵け繝ｪ繧｢
	SetByte(a5 + 3, 0);
	SetByte(a5 + 4, 0);

	// Unit numberacquire
	unit = GetByte(a5 + 1);

	// 繧ｳ繝槭Φ繝臥佐蠕
	command = GetByte(a5 + 2);

	// 繧ｹ繝ｬ繝繝牙ｾ讖滓ｺ門ｙ
	m_bReady = FALSE;
	::ResetEvent(m_hEventReady);

	// Execute碁幕蟋九う繝吶Φ繝医そ繝繝
	::SetEvent(m_hEventStart);

	// 繝槭Ν繝√せ繝ｬ繝繝蛾幕蟋玖ｦ∵ｱゅ′譚･繧九∪縺ｧ縺ｯ螳溯ｳｪ繧ｷ繝ｳ繧ｰ繝ｫ繧ｹ繝ｬ繝繝峨→縺励※謖ｯ繧玖槭≧
	DWORD nResult = ::WaitForSingleObject(m_hEventReady, INFINITE);
	ASSERT(nResult == WAIT_OBJECT_0);	// 蠢ｵ縺ｮ縺溘ａ
}

#ifdef WINDRV_SUPPORT_COMPATIBLE
//---------------------------------------------------------------------------
//
//	Command execute (WINDRVCompatible)
//
//---------------------------------------------------------------------------
DWORD FASTCALL CWindrv::ExecuteCompatible(DWORD nA5)
{
	ASSERT(this);
	ASSERT(nA5 <= 0xFFFFFF);

	// 繝ｪ繧ｯ繧ｨ繧ｹ繝医倥ャ繝縺ｮ繧｢繝峨Ξ繧ｹ
	a5 = nA5;

	// Error諠蝣ｱ繧偵け繝ｪ繧｢
	SetByte(a5 + 3, 0);
	SetByte(a5 + 4, 0);

	// Unit numberacquire
	unit = GetByte(a5 + 1);

	// 繧ｳ繝槭Φ繝臥佐蠕
	command = GetByte(a5 + 2);

	// Command execute
	ExecuteCommand();

	return GetByte(a5 + 3) | (GetByte(a5 + 4) << 8);
}
#endif // WINDRV_SUPPORT_COMPATIBLE

//---------------------------------------------------------------------------
//
//	繧ｳ繝槭Φ繝牙ｮ御ｺ繧貞ｾ縺溘★縺ｫVM繧ｹ繝ｬ繝繝牙ｮ溯｡悟埼幕
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::LockXM()
{
	ASSERT(this);
	if (m_bReady && windrv) {
		windrv->HostLockVM();
	}
}
void FASTCALL CWindrv::UnlockXM()
{
	ASSERT(this);
	if (m_bReady && windrv) {
		windrv->HostUnlockVM();
	}
}
void FASTCALL CWindrv::Ready()
{
	ASSERT(this);
	ASSERT(m_hEventReady);

	m_bReady = TRUE;
	::SetEvent(m_hEventReady);
}

//---------------------------------------------------------------------------
//
//	繧ｹ繝ｬ繝繝牙ｮ溯｡碁幕蟋九昴う繝ｳ繝
//
//---------------------------------------------------------------------------
DWORD __stdcall CWindrv::Run(void* pThis)
{
	ASSERT(pThis);

	((CWindrv*)pThis)->Runner();

	::ExitThread(0);
	return 0;
}

//---------------------------------------------------------------------------
//
//	繧ｹ繝ｬ繝繝牙ｮ滉ｽ
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Runner()
{
	ASSERT(this);
	ASSERT(m_hEventStart);
	ASSERT(m_hEventReady);
	//ASSERT(m_bTerminate == FALSE);
	// 繧ｹ繝ｬ繝繝蛾幕蟋狗峩蠕後↓縺縺阪↑繧概erminate縺吶ｋ縺ｨ縲√％縺ｮ譎らせ縺ｧ m_bTerminate 縺
	// TRUE縺ｨ縺ｪ繧句庄閭ｽ諤ｧ縺碁ｫ倥＞縲よ凾髢鍋ｵ碁℃縺ｫ繧医▲縺ｦEnd縺励∫ｵゆｺ縺ｮ迸ｬ髢薙↓蜷梧悄縺励※
	// 縺繧九◆繧、SSERT縺ｪ縺励〒繧ょ撫鬘後↑縺縲

	for (;;) {
		DWORD nResult = ::WaitForSingleObject(m_hEventStart, INFINITE);
		if (nResult != WAIT_OBJECT_0) {
			ASSERT(FALSE);	// 蠢ｵ縺ｮ縺溘ａ
			break;
		}
		if (m_bTerminate) break;

		// Execute
		ExecuteCommand();

		// Execute檎ｵゆｺ蜑阪↓騾夂衍
		Ready();

		// Execute悟ｮ御ｺ
		m_bExecute = FALSE;
	}

	Ready();	// 蠢ｵ縺ｮ縺溘ａ
}

//===========================================================================
//
//	Command handler邂｡逅
//
//===========================================================================

//---------------------------------------------------------------------------
//
//	Initialize
//
//	蜈ｨ繧ｹ繝ｬ繝繝臥｢ｺ菫昴＠縲∝ｾ讖溽憾諷九↓縺吶ｋ縲
//
//---------------------------------------------------------------------------
void FASTCALL CWindrvManager::Init(Windrv* pWindrv, Memory* pMemory)
{
	ASSERT(this);
	ASSERT(pWindrv);
	ASSERT(pMemory);

	for (int i = 0; i < WINDRV_THREAD_MAX; i++) {
		m_pThread[i] = new CWindrv(pWindrv, pMemory, i);
		m_pThread[i]->Start();
	}
}

//---------------------------------------------------------------------------
//
//	End
//
//	All縺ｮ繧ｹ繝ｬ繝繝峨ｒ蛛懈ｭ｢縺輔○繧九
//
//---------------------------------------------------------------------------
void FASTCALL CWindrvManager::Clean()
{
	ASSERT(this);

	for (int i = 0; i < WINDRV_THREAD_MAX; i++) {
		ASSERT(m_pThread[i]);	// 蠢ｵ縺ｮ縺溘ａ
		delete m_pThread[i];
		m_pThread[i] = NULL;
	}
}

//---------------------------------------------------------------------------
//
//	繝ｪ繧ｻ繝繝
//
//	Execute御ｸｭ縺ｮ繧ｹ繝ｬ繝繝峨ｮ縺ｿ蜀崎ｵｷ蜍輔＆縺帙ｋ縲
//
//---------------------------------------------------------------------------
void FASTCALL CWindrvManager::Reset()
{
	ASSERT(this);

	for (int i = 0; i < WINDRV_THREAD_MAX; i++) {
		ASSERT(m_pThread[i]);	// 蠢ｵ縺ｮ縺溘ａ
		if (m_pThread[i]->isAlloc()) {
			m_pThread[i]->Terminate();
			m_pThread[i]->Start();
		}
	}
}

//---------------------------------------------------------------------------
//
//	遨ｺ縺阪せ繝ｬ繝繝臥｢ｺ菫
//
//---------------------------------------------------------------------------
CWindrv* FASTCALL CWindrvManager::Alloc()
{
	ASSERT(this);

	for (int i = 0; i < WINDRV_THREAD_MAX; i++) {
		if (m_pThread[i]->isAlloc() == FALSE) {
			m_pThread[i]->SetAlloc(TRUE);
			return m_pThread[i];
		}
	}

	return NULL;
}

//---------------------------------------------------------------------------
//
//	繧ｹ繝ｬ繝繝画､懃ｴ｢
//
//---------------------------------------------------------------------------
CWindrv* FASTCALL CWindrvManager::Search(DWORD nHandle)
{
	ASSERT(this);

	if (nHandle >= WINDRV_THREAD_MAX) return NULL;
	return m_pThread[nHandle];
}

//---------------------------------------------------------------------------
//
//	繧ｹ繝ｬ繝繝蛾幕謾ｾ
//
//---------------------------------------------------------------------------
void FASTCALL CWindrvManager::Free(CWindrv* p)
{
	ASSERT(this);
	ASSERT(p);

	p->SetAlloc(FALSE);
}

//===========================================================================
//
//	Windrv
//
//===========================================================================

//---------------------------------------------------------------------------
//
//	繧ｳ繝ｳ繧ｹ繝医Λ繧ｯ繧ｿ
//
//---------------------------------------------------------------------------
Windrv::Windrv(VM *p) : MemDevice(p)
{
	// 繝繝舌う繧ｹID繧貞晄悄蛹
	dev.id = MAKEID('W', 'D', 'R', 'V');
	dev.desc = "Windrv";

	// 髢句ｧ九い繝峨Ξ繧ｹ縲∫ｵゆｺ繧｢繝峨Ξ繧ｹ
	memdev.first = 0xe9e000;
	memdev.last = 0xe9ffff;
}

//---------------------------------------------------------------------------
//
//	Initialize
//
//---------------------------------------------------------------------------
BOOL FASTCALL Windrv::Init()
{
	ASSERT(this);

	// 蝓ｺ譛ｬ繧ｯ繝ｩ繧ｹ
	if (!MemDevice::Init()) {
		return FALSE;
	}

	// 繧ｰ繝ｭ繝ｼ繝舌Ν繝輔Λ繧ｰ繧貞晄悄蛹
	windrv.enable = WINDRV_MODE_NONE;

	// 繝峨Λ繧､繝0縲√ヵ繧｡繧､繝ｫ繧ｷ繧ｹ繝繝辟｡縺
	windrv.drives = 0;
	windrv.fs = NULL;
	windrv.lock_vm_cb = NULL;
	windrv.unlock_vm_cb = NULL;
	windrv.sync_user = NULL;

	// 繧ｹ繝ｬ繝繝牙晄悄蛹
	Memory* memory = (Memory*)vm->SearchDevice(MAKEID('M', 'E', 'M', ' '));
	ASSERT(memory);
	m_cThread.Init(this, memory);

	return TRUE;
}

//---------------------------------------------------------------------------
//
//	繧ｯ繝ｪ繝ｼ繝ｳ繧｢繝繝
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::Cleanup()
{
	ASSERT(this);

	// 繧ｹ繝ｬ繝繝牙ｨrelease
	m_cThread.Clean();

	// 繝輔ぃ繧､繝ｫ繧ｷ繧ｹ繝繝縺後≠繧後ｰ縲√Μ繧ｻ繝繝
	if (windrv.fs) {
		windrv.fs->Reset();
	}

	// 蝓ｺ譛ｬ繧ｯ繝ｩ繧ｹ縺ｸ
	MemDevice::Cleanup();
}

//---------------------------------------------------------------------------
//
//	繝ｪ繧ｻ繝繝
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::Reset()
{
	ASSERT(this);

	LOG(Log::Normal, "繝ｪ繧ｻ繝繝");

	// 繧ｹ繝ｬ繝繝峨′Execute御ｸｭ縺ｧ縺ゅｌ縺ｰ縲√Μ繧ｻ繝繝
	m_cThread.Reset();

	// 繝輔ぃ繧､繝ｫ繧ｷ繧ｹ繝繝縺後≠繧後ｰ縲√Μ繧ｻ繝繝
	if (windrv.fs) {
		windrv.fs->Reset();
	}

	// 繝峨Λ繧､繝匁焚Initialize
	windrv.drives = 0;
}

//---------------------------------------------------------------------------
//
//	繧ｻ繝ｼ繝
//
//---------------------------------------------------------------------------
BOOL FASTCALL Windrv::Save(Fileio *fio, int ver)
{
	ASSERT(this);
	LOG(Log::Normal, "繧ｻ繝ｼ繝");
	(void)fio;
	(void)ver;
	
	return TRUE;
}

//---------------------------------------------------------------------------
//
//	繝ｭ繝ｼ繝
//
//---------------------------------------------------------------------------
BOOL FASTCALL Windrv::Load(Fileio *fio, int ver)
{
	ASSERT(this);
	LOG(Log::Normal, "繝ｭ繝ｼ繝");
	(void)fio;
	(void)ver;
	return TRUE;
}

//---------------------------------------------------------------------------
//
//	險ｭ螳夐←逕ｨ
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::ApplyCfg(const Config* pConfig)
{
	ASSERT(this);
	ASSERT(pConfig);
	LOG(Log::Normal, "險ｭ螳夐←逕ｨ");

	// 蜍穂ｽ懊ヵ繝ｩ繧ｰ繧定ｨｭ螳
	windrv.enable = pConfig->windrv_enable;
}

//---------------------------------------------------------------------------
//
//	Device read
//
//---------------------------------------------------------------------------
DWORD FASTCALL Windrv::ReadByte(DWORD addr)
{
	ASSERT(this);
	ASSERT((addr >= memdev.first) && (addr <= memdev.last));

	// 繝昴ｼ繝1
	if (addr == 0xE9F001) {
		return StatusAsynchronous();
	}

	DWORD result = ReadOnly(addr);

#ifdef WINDRV_LOG
	switch (result) {
	case 'X':
		LOG(Log::Normal, "Windrv繝昴ｼ繝 譛ｪ繧ｵ繝昴ｼ繝");
		break;
	case 'Y':
		LOG(Log::Normal, "Windrv繝昴ｼ繝 蛻ｩ逕ｨ蜿ｯｿｽ");
		break;
#ifdef WINDRV_SUPPORT_COMPATIBLE
	case 'W':
		LOG(Log::Normal, "Windrv繝昴ｼ繝 Compatible蜍穂ｽ");
		break;
#endif // WINDRV_SUPPORT_COMPATIBLE
	}
#endif // WINDRV_LOG

	if (result == 0xFF) {
		cpu->BusErr(addr, TRUE);
	}

	return result;
}

//---------------------------------------------------------------------------
//
//	Read縺ｮ縺ｿ
//
//---------------------------------------------------------------------------
DWORD FASTCALL Windrv::ReadOnly(DWORD addr) const
{
	ASSERT(this);
	ASSERT((addr >= memdev.first) && (addr <= memdev.last));

	// 隴伜挨繝昴ｼ繝井ｻ･螟悶ｯ-1
	if (addr != 0xE9F000) {
		return 0xFF;
	}

	switch (windrv.enable) {
	case WINDRV_MODE_DUAL:
	case WINDRV_MODE_ENABLE:
		return 'Y';			// WindrvXM

	case WINDRV_MODE_COMPATIBLE:
#ifdef WINDRV_SUPPORT_COMPATIBLE
		return 'W';			// WINDRVCompatible
#endif // WINDRV_SUPPORT_COMPATIBLE

	case WINDRV_MODE_NONE:
		return 'X';			// 菴ｿ逕ｨ荳榊庄 (I/O遨ｺ髢薙ｯ蟄伜惠縺吶ｋ)
	}

	// I/O遨ｺ髢薙′蟄伜惠縺励↑縺蝣ｴ蜷医ｯ-1
	return 0xFF;
}

//---------------------------------------------------------------------------
//
//	Device write
//
//	windrv繝昴ｼ繝医∈縺ｮWrite蠕後‥0.w縺ｧ繝ｪ繧ｶ繝ｫ繝医ｒ騾夂衍縺吶ｋ縲
//
//	荳贋ｽ8bit縺ｯ谺｡縺ｮ騾壹ｊ縲
//		$1x	Error(荳ｭ豁｢縺ｮ縺ｿ)
//		$2x	Error(蜀榊ｮ溯｡後ｮ縺ｿ)
//		$3x	Error(蜀榊ｮ溯｡鯉ｼ荳ｭ豁｢)
//		$4x	Error(辟｡隕悶ｮ縺ｿ)
//		$5x	Error(辟｡隕厄ｼ荳ｭ豁｢)
//		$6x	Error(辟｡隕厄ｼ蜀榊ｮ溯｡)
//		$7x	Error(辟｡隕厄ｼ蜀榊ｮ溯｡鯉ｼ荳ｭ豁｢)
//	荳倶ｽ8bit縺ｯ谺｡縺ｮ騾壹ｊ縲
//		$01	Invalid縺ｪUnit number繧呈欠螳壹＠縺.
//		$02	繝繧｣繧ｹ繧ｯ縺悟･縺｣縺ｦ縺縺ｪ縺.
//		$03	繝繝舌う繧ｹ繝峨Λ繧､繝舌↓Invalid縺ｪ繧ｳ繝槭Φ繝峨ｒ謖螳壹＠縺.
//		$04	CRC Error.
//		$05	繝繧｣繧ｹ繧ｯ縺ｮ邂｡逅鬆伜沺縺檎ｴ螢翫＆繧後※縺繧.
//		$06	SeekError.
//		$07	Invalid縺ｪ繝｡繝繧｣繧｢.
//		$08	繧ｻ繧ｯ繧ｿ縺瑚ｦ九▽縺九ｉ縺ｪ縺.
//		$09	繝励Μ繝ｳ繧ｿ縺檎ｹ九′縺｣縺ｦ縺縺ｪ縺.
//		$0a	WriteError.
//		$0b	ReadError.
//		$0c	縺昴ｮ莉悶ｮError.
//		$0d	繝ｩ繧､繝医励Ο繝繧ｯ繝(繝励Ο繝繧ｯ繝医ｒ螟悶＠縺ｦ蜷後§繝繧｣繧ｹ繧ｯ繧貞･繧後ｋ).
//		$0e	Write荳榊庄閭ｽ.
//		$0f	繝輔ぃ繧､繝ｫAttribute change.
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::WriteByte(DWORD addr, DWORD data)
{
	ASSERT(this);
	ASSERT((addr >= memdev.first) && (addr <= memdev.last));

	// 繧ｵ繝昴ｼ繝域凾縺ｮ縺ｿ繝昴ｼ繝亥愛螳
	switch (windrv.enable) {
	case WINDRV_MODE_DUAL:
	case WINDRV_MODE_ENABLE:
		switch (addr) {
		case 0xE9F000:
#ifdef WINDRV_SUPPORT_COMPATIBLE
			if (windrv.enable == WINDRV_MODE_DUAL) {
				Execute();	// 蜿ｯ閭ｽ縺ｪ繧峨％縺薙□縺代〒繧よｮ九＠縺溘＞
			}
#endif // WINDRV_SUPPORT_COMPATIBLE
			return;		// 繝昴ｼ繝域悴螳溯｣縺ｧ繧ゅヰ繧ｹError縺ｫ縺励↑縺(驥崎ｦ)
		case 0xE9F001:
			switch (data) {
			case 0x00: ExecuteAsynchronous(); return;
			case 0xFF: ReleaseAsynchronous(); return;
			}
			return;		// 荳肴ｭ｣縺ｪ蛟､縺ｮWrite縺ｧ繧ゅヰ繧ｹError縺ｫ縺励↑縺(諡｡蠑ｵ逕ｨ)
		}
		break;

	case WINDRV_MODE_COMPATIBLE:
#ifdef WINDRV_SUPPORT_COMPATIBLE
		switch (addr) {
		case 0xE9F000:
			Execute();
			return;
		}
		break;
#endif // WINDRV_SUPPORT_COMPATIBLE

	case WINDRV_MODE_NONE:
		switch (addr) {
		case 0xE9F000:
		case 0xE9F001:
			return;		// 繝昴ｼ繝医い繝峨Ξ繧ｹ縺ｮ縺ｿ螳溯｣ (譌ｧ繝舌ｼ繧ｸ繝ｧ繝ｳ縺ｮXM6縺ｨ縺ｮCompatible諤ｧ縺ｮ縺溘ａ)
		}
		break;
	}

	// Write蜈医′縺ｪ縺代ｌ縺ｰ繝舌せError
	cpu->BusErr(addr, FALSE);
	return;
}

#ifdef WINDRV_SUPPORT_COMPATIBLE
//---------------------------------------------------------------------------
//
//	Command handler
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::Execute()
{
	ASSERT(this);

	// 繝ｪ繧ｯ繧ｨ繧ｹ繝医倥ャ繝蜿励￠蜿悶ｊ
	CPU::cpu_t reg;
	cpu->GetCPU(&reg);
	DWORD a5 = reg.areg[5];
	ASSERT(a5 <= 0xFFFFFF);

	// Execute
	CWindrv* ps = m_cThread.Alloc();
	ASSERT(ps);
	DWORD result = ps->ExecuteCompatible(a5);
	m_cThread.Free(ps);

	// WINDRVCompatible蜍穂ｽ懊ｮ縺溘ａD0.L險ｭ螳
	reg.dreg[0] = result;
	cpu->SetCPU(&reg);

	// 蜷梧悄蝙九ｯAll縺ｮ繧ｳ繝槭Φ繝峨〒128us繧呈ｶ郁ｲｻ
	scheduler->Wait(128);	// TODO: Confirm縺ｪ蛟､繧堤ｮ怜ｺ縺吶ｋ
}
#endif // WINDRV_SUPPORT_COMPATIBLE

//---------------------------------------------------------------------------
//
//	Command execute碁幕蟋 髱槫酔譛
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::ExecuteAsynchronous()
{
	ASSERT(this);

	// 繝ｪ繧ｯ繧ｨ繧ｹ繝医倥ャ繝蜿励￠蜿悶ｊ
	CPU::cpu_t reg;
	cpu->GetCPU(&reg);
	DWORD a5 = reg.areg[5];
	ASSERT(a5 <= 0xFFFFFF);

	// 遨ｺ縺阪せ繝ｬ繝繝峨ｒ謐懊☆
	CWindrv* thread = m_cThread.Alloc();
	if (thread) {
		// 繧ｹ繝ｬ繝繝牙ｮ溯｡碁幕蟋
		thread->Execute(a5);
		reg.dreg[0] = thread->GetHandle();
	} else {
		// 繧ｹ繝ｬ繝繝峨′隕九▽縺九ｉ縺ｪ縺代ｌ縺ｰ-1
		reg.dreg[0] = (DWORD)-1;
		::Sleep(0);		// 繧ｹ繝ｬ繝繝牙ｮ溯｡梧ｨｩ繧剃ｸ迸ｬ遘ｻ縺
	}

	// Handle繧偵そ繝繝医＠縺ｦ蜊ｳEnd
	cpu->SetCPU(&reg);
}

//---------------------------------------------------------------------------
//
//	繧ｹ繝繝ｼ繧ｿ繧ｹacquire 髱槫酔譛
//
//---------------------------------------------------------------------------
DWORD FASTCALL Windrv::StatusAsynchronous()
{
	ASSERT(this);

	// Handle蜿励￠蜿悶ｊ
	CPU::cpu_t reg;
	cpu->GetCPU(&reg);
	DWORD handle = reg.dreg[0];

	// 隧ｲ蠖薙☆繧九ワ繝ｳ繝峨Ν縺ｮ繧ｹ繝繝ｼ繧ｿ繧ｹ繧堤佐蠕
	CWindrv* thread = m_cThread.Search(handle);
	if (thread) {
		if (thread->isExecute()) {
			::Sleep(0);		// 繧ｹ繝ｬ繝繝牙ｮ溯｡梧ｨｩ繧剃ｸ迸ｬ遘ｻ縺
			return 0;		// 縺ｾ縺Execute御ｸｭ縺ｪ繧0
		}

		return 1;			// Execute悟ｮ御ｺ縺ｪ繧1
	}

	return 0xFF;			// 荳肴ｭ｣縺ｪHandle縺ｪ繧-1
}

//---------------------------------------------------------------------------
//
//	Handlerelease 髱槫酔譛
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::ReleaseAsynchronous()
{
	ASSERT(this);

	// D0.L(Handle)蜿励￠蜿悶ｊ
	CPU::cpu_t reg;
	cpu->GetCPU(&reg);
	DWORD handle = reg.dreg[0];

	// 隧ｲ蠖薙☆繧九ワ繝ｳ繝峨Ν繧帝幕謾ｾ
	CWindrv* thread = m_cThread.Search(handle);
	if (thread) {
		m_cThread.Free(thread);
	}
}

//---------------------------------------------------------------------------
//
//	Command execute
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::ExecuteCommand()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);

	if (command == 0x40) {
		// $40 - Initialize
		InitDrive();
		return;
	}

	if (windrv->isInvalidUnit(unit)) {
		LockXM();

		// Invalid縺ｪUnit number繧呈欠螳壹＠縺
		SetResult(FS_FATAL_INVALIDUNIT);

		UnlockXM();
		return;
	}

	// 繧ｳ繝槭Φ繝牙蟯
	switch (command & 0x7F) {
		case 0x41: CheckDir(); return;		// $41 - Directory check
		case 0x42: MakeDir(); return;		// $42 - Make directory
		case 0x43: RemoveDir(); return;		// $43 - Remove directory
		case 0x44: Rename(); return;		// $44 - 繝輔ぃ繧､繝ｫ蜷榊､画峩
		case 0x45: Delete(); return;		// $45 - 繝輔ぃ繧､繝ｫDelete
		case 0x46: Attribute(); return;		// $46 - 繝輔ぃ繧､繝ｫAttribute蜿門ｾ/險ｭ螳
		case 0x47: Files(); return;			// $47 - 繝輔ぃ繧､繝ｫSearch(First)
		case 0x48: NFiles(); return;		// $48 - 繝輔ぃ繧､繝ｫSearch(Next);
		case 0x49: Create(); return;		// $49 - 繝輔ぃ繧､繝ｫCreate
		case 0x4A: Open(); return;			// $4A - 繝輔ぃ繧､繝ｫOpen
		case 0x4B: Close(); return;			// $4B - 繝輔ぃ繧､繝ｫClose
		case 0x4C: Read(); return;			// $4C - 繝輔ぃ繧､繝ｫRead
		case 0x4D: Write(); return;			// $4D - 繝輔ぃ繧､繝ｫWrite
		case 0x4E: Seek(); return;			// $4E - 繝輔ぃ繧､繝ｫSeek
		case 0x4F: TimeStamp(); return;		// $4F - 繝輔ぃ繧､繝ｫ譖ｴ譁ｰ譎ょ綾縺ｮ蜿門ｾ/險ｭ螳
		case 0x50: GetCapacity(); return;	// $50 - Get capacity
		case 0x51: CtrlDrive(); return;		// $51 - 繝峨Λ繧､繝門宛蠕｡/迥ｶ諷区､懈渊
		case 0x52: GetDPB(); return;		// $52 - Get DPB
		case 0x53: DiskRead(); return;		// $53 - 繧ｻ繧ｯ繧ｿRead
		case 0x54: DiskWrite(); return;		// $54 - 繧ｻ繧ｯ繧ｿWrite
		case 0x55: IoControl(); return;		// $55 - IOCTRL
		case 0x56: Flush(); return;			// $56 - 繝輔Λ繝繧ｷ繝･
		case 0x57: CheckMedia(); return;	// $57 - 繝｡繝繧｣繧｢莠､謠帙メ繧ｧ繝繧ｯ
		case 0x58: Lock(); return;			// $58 - Lock drive
	}


	LockXM();

	// 繝繝舌う繧ｹ繝峨Λ繧､繝舌↓Invalid縺ｪ繧ｳ繝槭Φ繝峨ｒ謖螳壹＠縺
	SetResult(FS_FATAL_INVALIDCOMMAND);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	繝輔ぃ繧､繝ｫ繧ｷ繧ｹ繝繝險ｭ螳
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::SetHostSyncCallbacks(host_sync_callback_t lock_vm_cb, host_sync_callback_t unlock_vm_cb, void *user)
{
	ASSERT(this);
	windrv.lock_vm_cb = lock_vm_cb;
	windrv.unlock_vm_cb = unlock_vm_cb;
	windrv.sync_user = user;
}
void FASTCALL Windrv::HostLockVM() const
{
	ASSERT(this);
	if (windrv.lock_vm_cb) {
		windrv.lock_vm_cb(windrv.sync_user);
	}
}
void FASTCALL Windrv::HostUnlockVM() const
{
	ASSERT(this);
	if (windrv.unlock_vm_cb) {
		windrv.unlock_vm_cb(windrv.sync_user);
	}
}
void FASTCALL Windrv::SetFileSys(FileSys *fs)
{
	ASSERT(this);

	// 迴ｾ蝨ｨ蟄伜惠縺励◆蝣ｴ蜷医∽ｸ閾ｴ縺励↑縺代ｌ縺ｰ荳譌ｦReset
	if (windrv.fs) {
		if (windrv.fs != fs) {
			// Reset
			Reset();
		}
	}

	// NULL or set
	windrv.fs = fs;
}

//---------------------------------------------------------------------------
//
//	繝輔ぃ繧､繝ｫ繧ｷ繧ｹ繝繝險ｭ螳
//
//---------------------------------------------------------------------------
BOOL FASTCALL Windrv::isInvalidUnit(DWORD unit) const
{
	ASSERT(this);

	if (unit >= windrv.drives) return TRUE;	// 蠅逡後ｈ繧雁､ｧ縺阪￠繧後ｰ荳肴ｭ｣縺ｪUnit number

	ASSERT(windrv.fs);
	// 蜴ｳ蟇縺ｫ繧繧九↑繧峨∝ｯｾ雎｡縺ｨ縺ｪ繧祈ileSys縺ｮ蜍穂ｽ懊Δ繝ｼ繝峨ｒ蝠上＞蜷医ｏ縺帙ｋ縺ｹ縺阪□縺後
	// 繧｢繧ｯ繧ｻ繧ｹ荳榊庄閭ｽ縺ｪ繝輔ぃ繧､繝ｫ繧ｷ繧ｹ繝繝縺ｯ縺昴ｂ縺昴ｂ逋ｻ骭ｲ縺輔ｌ縺ｪ縺縺ｮ縺ｧ繝√ぉ繝繧ｯ荳崎ｦ
	return FALSE;
}

//---------------------------------------------------------------------------
//
//	$40 - Initialize
//
//	in	(offset size)
//		 0	1.b	螳壽焚(22)
//		 2	1.b	繧ｳ繝槭Φ繝($40/$c0)
//		18	1.l	Parameter address
//		22	1.b	Drive letter
//	out	(offset size)
//		 3	1.b	Error code (low)
//		 4	1.b	縲	    (荳贋ｽ)
//		13	1.b	繝ｦ繝九ャ繝域焚
//		14	1.l	繝繝舌う繧ｹ繝峨Λ繧､繝舌ｮEnd繧｢繝峨Ξ繧ｹ + 1
//
//	縲繝ｭ繝ｼ繧ｫ繝ｫ繝峨Λ繧､繝悶ｮ繧ｳ繝槭Φ繝 0 縺ｨWhen ready邨縺ｿ霎ｼ縺ｿ譎ゅ↓蜻ｼ縺ｰ繧後ｋ縺後。PB 蜿
//	縺ｳ縺昴ｮ繝昴う繝ｳ繧ｿ縺ｮ驟榊励ｒ逕ｨ諢上☆繧句ｿ隕√ｯ縺ｪ縺.
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::InitDrive()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->GetFilesystem());

#ifdef WINDRV_LOG
	Log(Log::Normal, "$40 - Initialize");
#endif // WINDRV_LOG

	LockXM();

	// 繝吶ｼ繧ｹ繝峨Λ繧､繝門錐繧堤佐蠕
	DWORD base = GetByte(a5 + 22);
	ASSERT(base < 26);
	// DRIVE繧ｳ繝槭Φ繝峨〒鬆蠎上′螟峨ｏ繧九→蛟､縺檎┌蜉ｹ縺ｫ縺ｪ繧九◆繧√『indrv.base縺ｯ蟒豁｢

	// 繧ｪ繝励す繝ｧ繝ｳ蜀螳ｹ繧堤佐蠕
	BYTE chOption[256];
	GetParameter(GetAddr(a5 + 18), chOption, sizeof(chOption));

	UnlockXM();

	// Human68k蛛ｴ縺ｧ蛻ｩ逕ｨ蜿ｯ閭ｽ縺ｪ繝峨Λ繧､繝匁焚縺ｮ遽蝗ｲ縺ｧ縲√ヵ繧｡繧､繝ｫ繧ｷ繧ｹ繝繝繧呈ｧ狗ｯ
	DWORD max_unit = windrv->GetFilesystem()->Init(this, 26 - base, chOption);

	// 螳滄圀縺ｫ遒ｺ菫昴＆繧後◆繝ｦ繝九ャ繝域焚繧剃ｿ晏ｭ
	windrv->SetUnitMax(max_unit);

#ifdef WINDRV_LOG
	Log(Log::Detail, "繝吶ｼ繧ｹ繝峨Λ繧､繝:%c 繧ｵ繝昴ｼ繝医ラ繝ｩ繧､繝匁焚:%d",
					'A' + base, max_unit);
#endif // WINDRV_LOG

	LockXM();

	// Set drive count
	SetByte(a5 + 13, max_unit);

	// Result
	SetResult(0);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$41 - Directory check
//
//	in
//		14	1.L	NAMESTS structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::CheckDir()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameStsPath(GetAddr(a5 + 14), &ns);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$41 %d Directory check", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->CheckDir(this, &ns);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$42 - Make directory
//
//	in
//		14	1.L	NAMESTS structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::MakeDir()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$42 %d Make directory", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->MakeDir(this, &ns);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$43 - Remove directory
//
//	in
//		14	1.L	NAMESTS structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::RemoveDir()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$43 %d Remove directory", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->RemoveDir(this, &ns);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$44 - 繝輔ぃ繧､繝ｫ蜷榊､画峩
//
//	in
//		14	1.L	NAMESTS structure address 譌ｧ繝輔ぃ繧､繝ｫ蜷
//		18	1.L	NAMESTS structure address 譁ｰ繝輔ぃ繧､繝ｫ蜷
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Rename()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);
	Human68k::namests_t ns_new;
	GetNameSts(GetAddr(a5 + 18), &ns_new);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$44 %d 繝輔ぃ繧､繝ｫ蜷榊､画峩", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->Rename(this, &ns, &ns_new);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$45 - 繝輔ぃ繧､繝ｫDelete
//
//	in
//		14	1.L	NAMESTS structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Delete()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$45 %d 繝輔ぃ繧､繝ｫDelete", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->Delete(this, &ns);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$46 - 繝輔ぃ繧､繝ｫAttribute蜿門ｾ/險ｭ螳
//
//	in
//		12	1.B	隱ｭ縺ｿ蜃ｺ縺玲凾縺ｫ0x01縺ｫ縺ｪ繧九ｮ縺ｧpending
//		13	1.B	Attribute $FF縺縺ｨ隱ｭ縺ｿ蜃ｺ縺
//		14	1.L	NAMESTS structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Attribute()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);

	// 蟇ｾ雎｡Attribute
	DWORD attr = GetByte(a5 + 13);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$46 %d 繝輔ぃ繧､繝ｫAttribute蜿門ｾ/險ｭ螳 Attribute:%02X", unit, attr);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->Attribute(this, &ns, attr);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$47 - 繝輔ぃ繧､繝ｫSearch(First)
//
//	in	(offset size)
//		 0	1.b	Constant(26)
//		 1	1.b	Unit number
//		 2	1.b	繧ｳ繝槭Φ繝($47/$c7)
//		13	1.b	SearchAttribute
//		14	1.l	Filename buffer (namests format)
//		18	1.l	Search繝舌ャ繝輔ぃ(files 蠖｢蠑) 縺薙ｮ繝舌ャ繝輔ぃ縺ｫSearch騾比ｸｭ諠蝣ｱ縺ｨSearch邨先棡繧呈嶌縺崎ｾｼ繧
//	out	(offset size)
//		 3	1.b	Error code (low)
//		 4	1.b	縲	    (荳贋ｽ)
//		18	1.l	Result status
//
//	縲繝繧｣繝ｬ繧ｯ繝医Μ縺九ｉ謖螳壹ヵ繧｡繧､繝ｫ繧呈､懃ｴ｢縺吶ｋ. DOS _FILES 縺九ｉ蜻ｼ縺ｳ蜃ｺ縺輔ｌ繧.
//	縲Search縺ｫ螟ｱ謨励＠縺溷ｴ蜷医∬凶縺励￥縺ｯSearch縺ｫ謌仙粥縺励※繧ゅΡ繧､繝ｫ繝峨き繝ｼ繝峨′菴ｿ繧上ｌ縺ｦ
//	縺縺ｪ縺蝣ｴ蜷医ｯ縲∵ｬ｡蝗樊､懃ｴ｢譎ゅ↓蠢縺壼､ｱ謨励＆縺帙ｋ轤ｺ縺ｫSearch繝舌ャ繝輔ぃ縺ｮOffset縺ｫ
//	-1 繧呈嶌縺崎ｾｼ繧. Search縺梧仙粥縺励◆蝣ｴ蜷医ｯ隕九▽縺九▲縺溘ヵ繧｡繧､繝ｫ縺ｮ諠蝣ｱ繧定ｨｭ螳壹☆繧
//	縺ｨ蜈ｱ縺ｫ縲∵ｬ｡Search逕ｨ縺ｮ諠蝣ｱ縺ｮSector number縲＾ffset縲√Ν繝ｼ繝医ョ繧｣繝ｬ繧ｯ繝医Μ縺ｮ蝣ｴ
//	蜷医ｯ譖ｴ縺ｫ谿九ｊSector count繧定ｨｭ螳壹☆繧. Search繝峨Λ繧､繝悶ｻAttribute縲√ヱ繧ｹ蜷阪ｯ DOS 繧ｳ繝ｼ
//	繝ｫ蜃ｦ逅蜀縺ｧ險ｭ螳壹＆繧後ｋ縺ｮ縺ｧ譖ｸ縺崎ｾｼ繧蠢隕√ｯ縺ｪ縺.
//
//	<NAMESTS讒矩菴>
//	offset size
//	0	1.b	NAMWLD	0:繝ｯ繧､繝ｫ繝峨き繝ｼ繝峨↑縺 -1:繝輔ぃ繧､繝ｫ謖螳壹↑縺
//				(繝ｯ繧､繝ｫ繝峨き繝ｼ繝峨ｮ譁蟄玲焚)
//	1	1.b	NAMDRV	Drive letter(A=0,B=1,窶ｦ,Z=25)
//	2	65.b	NAMPTH	繝代せ('\'ｼ九≠繧後ｰ繧ｵ繝悶ョ繧｣繝ｬ繧ｯ繝医Μ蜷搾ｼ'\')
//	67	8.b	NAMNM1	繝輔ぃ繧､繝ｫ蜷(蜈磯ｭ 8 譁蟄)
//	75	3.b	NAMEXT	Extension
//	78	10.b	NAMNM2	繝輔ぃ繧､繝ｫ蜷(谿九ｊ縺ｮ 10 譁蟄)
//
// 繝代せ蛹ｺ蛻繧頑枚蟄励ｯ0x2F(/)繧0x5C(\)縺ｧ縺ｯ縺ｪ縺0x09(TAB)繧剃ｽｿ縺｣縺ｦ縺繧九ｮ縺ｧpending
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Files()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Search progress storage area
	DWORD nFiles = GetAddr(a5 + 18);
	Human68k::files_t info;
	GetFiles(nFiles, &info);
	//info.fatr =  (BYTE)GetByte(a5 + 13);	// Save search attribute (already written)

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$47 %d 繝輔ぃ繧､繝ｫSearch(First) Info:%X Attribute:%02X", unit, nFiles, info.fatr);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->Files(this, &ns, nFiles, &info);

	LockXM();

	// SearchReflect result
	if (nResult >= 0) {
		SetFiles(nFiles, &info);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$48 - 繝輔ぃ繧､繝ｫSearch(Next)
//
//	in
//		18	1.L	FILES讒矩菴薙い繝峨Ξ繧ｹ
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::NFiles()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Read work area
	DWORD nFiles = GetAddr(a5 + 18);
	Human68k::files_t info;
	GetFiles(nFiles, &info);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$48 - 繝輔ぃ繧､繝ｫSearch(Next) Info:%X", nFiles);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->NFiles(this, nFiles, &info);

	LockXM();

	// SearchReflect result
	if (nResult >= 0) {
		SetFiles(nFiles, &info);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$49 - 繝輔ぃ繧､繝ｫCreate(Create)
//
//	in
//		 1	1.B	Unit number
//		13	1.B	Attribute
//		14	1.L	NAMESTS structure address
//		18	1.L	繝｢繝ｼ繝 (0:_NEWFILE 1:_CREATE)
//		22	1.L	FCB structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Create()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);

	// Get FCB
	DWORD nFcb = GetAddr(a5 + 22);	// Save FCB address
	Human68k::fcb_t fcb;
	GetFcb(nFcb, &fcb);

	// Attribute
	DWORD attr = GetByte(a5 + 13);

	// Force overwrite mode
	BOOL force = (BOOL)GetLong(a5 + 18);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$49 %d 繝輔ぃ繧､繝ｫCreate FCB:%X Attribute:%02X Mode:%d", unit, nFcb, attr, force);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->Create(this, &ns, nFcb, &fcb, attr, force);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetFcb(nFcb, &fcb);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$4A - 繝輔ぃ繧､繝ｫOpen
//
//	in
//		 1	1.B	Unit number
//		14	1.L	NAMESTS structure address
//		22	1.L	FCB structure address
//				譌｢縺ｫFCB縺ｫ縺ｯ縺ｻ縺ｨ繧薙←縺ｮParameter縺瑚ｨｭ螳壽ｸ医∩
//				Time/date overwritten縺励◆迸ｬ髢薙ｮ繧ゅｮ縺ｫ縺ｪ縺｣縺ｦ繧九ｮ縺ｧ荳頑嶌縺
//				Size overwritten縺ｮ縺ｧ荳頑嶌縺
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Open()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get target file name
	Human68k::namests_t ns;
	GetNameSts(GetAddr(a5 + 14), &ns);

	// Get FCB
	DWORD nFcb = GetAddr(a5 + 22);	// Save FCB address
	Human68k::fcb_t fcb;
	GetFcb(nFcb, &fcb);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$4A %d 繝輔ぃ繧､繝ｫOpen FCB:%X Mode:%X", unit, nFcb, fcb.mode);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->Open(this, &ns, nFcb, &fcb);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetFcb(nFcb, &fcb);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$4B - 繝輔ぃ繧､繝ｫClose
//
//	in
//		22	1.L	FCB structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Close()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get FCB
	DWORD nFcb = GetAddr(a5 + 22);	// Save FCB address
	Human68k::fcb_t fcb;
	GetFcb(nFcb, &fcb);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$4B - 繝輔ぃ繧､繝ｫClose FCB:%X", nFcb);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->Close(this, nFcb, &fcb);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$4C - 繝輔ぃ繧､繝ｫRead
//
//	in
//		14	1.L	Read buffer
//		18	1.L	繧ｵ繧､繧ｺ 雋縺ｮ謨ｰ縺ｪ繧峨ヵ繧｡繧､繝ｫ繧ｵ繧､繧ｺ繧呈欠螳壹＠縺溘ｮ縺ｨ蜷後§
//		22	1.L	FCB structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Read()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get FCB
	DWORD nFcb = GetAddr(a5 + 22);	// Save FCB address
	Human68k::fcb_t fcb;
	GetFcb(nFcb, &fcb);

	// Read buffer
	DWORD nAddress = GetAddr(a5 + 14);

	// Read size
	DWORD nSize = GetLong(a5 + 18);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$4C - 繝輔ぃ繧､繝ｫRead FCB:%X 繧｢繝峨Ξ繧ｹ:%X 繧ｵ繧､繧ｺ:%d", nFcb, nAddress, nSize);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->Read(this, nFcb, &fcb, nAddress, nSize);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetFcb(nFcb, &fcb);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$4D - 繝輔ぃ繧､繝ｫWrite
//
//	in
//		14	1.L	Write buffer
//		18	1.L	繧ｵ繧､繧ｺ 雋縺ｮ謨ｰ縺ｪ繧峨ヵ繧｡繧､繝ｫ繧ｵ繧､繧ｺ繧呈欠螳壹＠縺溘ｮ縺ｨ蜷後§
//		22	1.L	FCB structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Write()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get FCB
	DWORD nFcb = GetAddr(a5 + 22);	// Save FCB address
	Human68k::fcb_t fcb;
	GetFcb(nFcb, &fcb);

	// Write buffer
	DWORD nAddress = GetAddr(a5 + 14);

	// Write size
	DWORD nSize = GetLong(a5 + 18);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$4D - 繝輔ぃ繧､繝ｫWrite FCB:%X 繧｢繝峨Ξ繧ｹ:%X 繧ｵ繧､繧ｺ:%d", nFcb, nAddress, nSize);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->Write(this, nFcb, &fcb, nAddress, nSize);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetFcb(nFcb, &fcb);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$4E - 繝輔ぃ繧､繝ｫSeek
//
//	in
//		12	1.B	Sometimes 0x2B 0縺ｮ縺ｨ縺阪ｂ縺ゅｋ
//		13	1.B	繝｢繝ｼ繝
//		18	1.L	Offset
//		22	1.L	FCB structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Seek()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get FCB
	DWORD nFcb = GetAddr(a5 + 22);	// Save FCB address
	Human68k::fcb_t fcb;
	GetFcb(nFcb, &fcb);

	// Seek mode
	DWORD nMode = GetByte(a5 + 13);

	// Seek offset
	DWORD nOffset = GetLong(a5 + 18);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$4E - 繝輔ぃ繧､繝ｫSeek FCB:%X 繝｢繝ｼ繝:%d Offset:%d", nFcb, nMode, nOffset);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->Seek(this, nFcb, &fcb, nMode, nOffset);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetFcb(nFcb, &fcb);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$4F - 繝輔ぃ繧､繝ｫTimestamp get/set/險ｭ螳
//
//	in
//		18	1.W	DATE
//		20	1.W	TIME
//		22	1.L	FCB structure address
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::TimeStamp()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get FCB
	DWORD nFcb = GetAddr(a5 + 22);	// Save FCB address
	Human68k::fcb_t fcb;
	GetFcb(nFcb, &fcb);

	// Get timestamp
	WORD nFatDate = (WORD)GetWord(a5 + 18);
	WORD nFatTime = (WORD)GetWord(a5 + 20);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$4F - 繝輔ぃ繧､繝ｫTimestamp get/set/險ｭ螳 FCB:%X 譎ょ綾:%04X%04X", nFcb, nFatDate, nFatTime);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->TimeStamp(this, nFcb, &fcb, nFatDate, nFatTime);

	LockXM();

	// Reflect result
	if ((nResult >> 16) != 0xFFFF) {
		SetFcb(nFcb, &fcb);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$50 - Get capacity
//
//	in	(offset size)
//		 0	1.b	Constant(26)
//		 1	1.b	Unit number
//		 2	1.b	繧ｳ繝槭Φ繝($50/$d0)
//		14	1.l	繝舌ャ繝輔ぃ繧｢繝峨Ξ繧ｹ
//	out	(offset size)
//		 3	1.b	Error code (low)
//		 4	1.b	縲	    (荳贋ｽ)
//		18	1.l	Result status
//
//	縲繝｡繝繧｣繧｢縺ｮ邱丞ｮｹ驥/遨ｺ縺榊ｮｹ驥上√け繝ｩ繧ｹ繧ｿ/繧ｻ繧ｯ繧ｿ繧ｵ繧､繧ｺ繧貞庶蠕励☆繧. 繝舌ャ繝輔ぃ
//	縺ｫ譖ｸ縺崎ｾｼ繧蜀螳ｹ縺ｯ莉･荳九ｮ騾壹ｊ. Result status縺ｨ縺励※菴ｿ逕ｨ蜿ｯ閭ｽ縺ｪ繝舌う繝域焚
//	繧定ｿ斐☆縺薙→.
//
//	offset size
//	0	1.w	Free clusters
//	2	1.w	Total clusters
//	4	1.w	1 繧ｯ繝ｩ繧ｹ繧ｿ蠖薙ｊ縺ｮSector count
//	6	1.w	Bytes per sector
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetCapacity()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

#ifdef WINDRV_LOG
	Log(Log::Normal, "$50 %d Get capacity", unit);
#endif // WINDRV_LOG

	LockXM();

	// Get buffer
	DWORD nCapacity = GetAddr(a5 + 14);
	Human68k::capacity_t cap;
	//GetCapacity(nCapacity, &cap);	// Get is unnecessary 蜃ｺ蜑崎ｿ騾 關ｽ譖ｸ縺咲┌逕ｨ

	UnlockXM();

	// Call file system
	int nResult = windrv->GetFilesystem()->GetCapacity(this, &cap);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetCapacity(nCapacity, &cap);
	}

	// Result
	SetResult(nResult);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Detail, "繝ｦ繝九ャ繝%d 遨ｺ縺榊ｮｹ驥 %d", unit, nResult);
#endif // WINDRV_LOG
}

//---------------------------------------------------------------------------
//
//	$51 - Drive control/status/Get status
//
//	in	(offset size)
//		 1	1.B	Unit number
//		13	1.B	迥ｶ諷	0: 迥ｶ諷区､懈渊 1: 繧､繧ｸ繧ｧ繧ｯ繝
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::CtrlDrive()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get drive status
	Human68k::ctrldrive_t ctrl;
	ctrl.status = (BYTE)GetByte(a5 + 13);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$51 %d Drive control/status/Get status Mode:%d", unit, ctrl.status);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->CtrlDrive(this, &ctrl);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetByte(a5 + 13, ctrl.status);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$52 - Get DPB
//
//	in	(offset size)
//		 0	1.b	Constant(26)
//		 1	1.b	Unit number
//		 2	1.b	繧ｳ繝槭Φ繝($52/$d2)
//		14	1.l	繝舌ャ繝輔ぃ繧｢繝峨Ξ繧ｹ(蜈磯ｭ繧｢繝峨Ξ繧ｹ + 2 繧呈欠縺)
//	out	(offset size)
//		 3	1.b	Error code (low)
//		 4	1.b	縲	    (荳贋ｽ)
//		18	1.l	Result status
//
//	縲謖螳壹Γ繝繧｣繧｢縺ｮ諠蝣ｱ繧 v1 蠖｢蠑 DPB 縺ｧ霑斐☆. 縺薙ｮ繧ｳ繝槭Φ繝峨〒險ｭ螳壹☆繧句ｿ隕
//	縺後≠繧区ュ蝣ｱ縺ｯ莉･荳九ｮ騾壹ｊ(諡ｬ蠑ｧ蜀縺ｯ DOS 繧ｳ繝ｼ繝ｫ縺瑚ｨｭ螳壹☆繧). 縺溘□縺励√ヰ繝繝
//	繧｡繧｢繝峨Ξ繧ｹ縺ｯOffset 2 繧呈欠縺励◆繧｢繝峨Ξ繧ｹ縺梧ｸ｡縺輔ｌ繧九ｮ縺ｧpending上☆繧九％縺ｨ.
//
//	offset size
//	 0	1.b	(Drive letter)
//	 1	1.b	(Unit number)
//	 2	1.w	Bytes per sector
//	 4	1.b	1 繧ｯ繝ｩ繧ｹ繧ｿ蠖薙ｊ縺ｮSector count - 1
//	 5	1.b	繧ｯ繝ｩ繧ｹ繧ｿ竊偵そ繧ｯ繧ｿ縺ｮ繧ｷ繝輔ヨ謨ｰ
//			bit 7 = 1 縺ｧ MS-DOS 蠖｢蠑 FAT(16bit Intel 驟榊)
//	 6	1.w	FAT 縺ｮ蜈磯ｭSector number
//	 8	1.b	FAT 鬆伜沺縺ｮ蛟区焚
//	 9	1.b	FAT 縺ｮ蜊繧√ｋSector count(隍蜀吝繧帝勁縺)
//	10	1.w	繝ｫ繝ｼ繝医ョ繧｣繝ｬ繧ｯ繝医Μ縺ｫ蜈･繧九ヵ繧｡繧､繝ｫ縺ｮ蛟区焚
//	12	1.w	繝繝ｼ繧ｿ鬆伜沺縺ｮ蜈磯ｭSector number
//	14	1.w	Total clusters + 1
//	16	1.w	繝ｫ繝ｼ繝医ョ繧｣繝ｬ繧ｯ繝医Μ縺ｮ蜈磯ｭSector number
//	18	1.l	(繝峨Λ繧､繝舌倥ャ繝縺ｮ繧｢繝峨Ξ繧ｹ)
//	22	1.b	(蟆乗枚蟄励ｮ迚ｩ逅繝峨Λ繧､繝門錐)
//	23	1.b	(DPB 菴ｿ逕ｨ繝輔Λ繧ｰ:蟶ｸ縺ｫ 0)
//	24	1.l	(谺｡縺ｮ DPB 縺ｮ繧｢繝峨Ξ繧ｹ)
//	28	1.w	(繧ｫ繝ｬ繝ｳ繝医ョ繧｣繝ｬ繧ｯ繝医Μ縺ｮ繧ｯ繝ｩ繧ｹ繧ｿ逡ｪ蜿ｷ:蟶ｸ縺ｫ 0)
//	30	64.b	(繧ｫ繝ｬ繝ｳ繝医ョ繧｣繝ｬ繧ｯ繝医Μ蜷)
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetDPB()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get DPB
	DWORD nDpb = GetAddr(a5 + 14);
	Human68k::dpb_t dpb;
	//GetDpb(nDpb, &dpb);	// Get is unnecessary 蜃ｺ蜑崎ｿ騾 關ｽ譖ｸ縺咲┌逕ｨ

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$52 %d Get DPB DPB:%X", unit, nDpb);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->GetDPB(this, &dpb);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetDpb(nDpb, &dpb);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$53 - 繧ｻ繧ｯ繧ｿRead
//
//	in	(offset size)
//		 1	1.B	Unit number
//		14	1.L	繝舌ャ繝輔ぃ繧｢繝峨Ξ繧ｹ
//		18	1.L	Sector count
//		22	1.L	Sector number
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::DiskRead()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	DWORD nAddress = GetAddr(a5 + 14);	// Address (upper bits are extension flag)
	DWORD nSize = GetLong(a5 + 18);		// Sector count
	DWORD nSector = GetLong(a5 + 22);	// Sector number

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$53 %d 繧ｻ繧ｯ繧ｿRead 繧｢繝峨Ξ繧ｹ:%X 繧ｻ繧ｯ繧ｿ:%X 蛟区焚:%X", unit, nAddress, nSector, nSize);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->DiskRead(this, nAddress, nSector, nSize);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$54 - 繧ｻ繧ｯ繧ｿWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::DiskWrite()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	DWORD nAddress = GetAddr(a5 + 14);	// Address (upper bits are extension flag)
	DWORD nSize = GetLong(a5 + 18);		// Sector count
	DWORD nSector = GetLong(a5 + 22);	// Sector number

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$53 %d 繧ｻ繧ｯ繧ｿWrite 繧｢繝峨Ξ繧ｹ:%X 繧ｻ繧ｯ繧ｿ:%X 蛟区焚:%X", unit, nAddress, nSector, nSize);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->DiskWrite(this, nAddress, nSector, nSize);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$55 - IOCTRL
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::IoControl()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

	LockXM();

	// Get IOCTRL
	DWORD nParameter = GetLong(a5 + 14);	// Parameter
	DWORD nFunction = GetWord(a5 + 18);		// Function number
	Human68k::ioctrl_t ioctrl;
	GetIoctrl(nParameter, nFunction, &ioctrl);

	UnlockXM();

#ifdef WINDRV_LOG
	Log(Log::Normal, "$55 %d IOCTRL Parameter:%X 讖滂ｿｽ:%X", unit, nParameter, nFunction);
#endif // WINDRV_LOG

	// Call file system
	int nResult = windrv->GetFilesystem()->IoControl(this, &ioctrl, nFunction);

	LockXM();

	// Reflect result
	if (nResult >= 0) {
		SetIoctrl(nParameter, nFunction, &ioctrl);
	}

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$56 - 繝輔Λ繝繧ｷ繝･
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Flush()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

#ifdef WINDRV_LOG
	Log(Log::Normal, "$56 %d 繝輔Λ繝繧ｷ繝･", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->Flush(this);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$57 - 繝｡繝繧｣繧｢莠､謠帙メ繧ｧ繝繧ｯ
//
//	in	(offset size)
//		 0	1.b	Constant(26)
//		 1	1.b	Unit number
//		 2	1.b	繧ｳ繝槭Φ繝($57/$d7)
//	out	(offset size)
//		 3	1.b	Error code (low)
//		 4	1.b	縲	    (荳贋ｽ)
//		18	1.l	Result status
//
//	縲繝｡繝繧｣繧｢縺御ｺ､謠帙＆繧後◆縺句凄縺九ｒ隱ｿ縺ｹ繧. 莠､謠帙＆繧後※縺縺溷ｴ蜷医ｮ繝輔か繝ｼ繝槭ャ繝
//	遒ｺ隱阪ｯ縺薙ｮ繧ｳ繝槭Φ繝牙縺ｧ陦後≧縺薙→.
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::CheckMedia()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

#ifdef WINDRV_LOG
	Log(Log::Normal, "$57 %d 繝｡繝繧｣繧｢莠､謠帙メ繧ｧ繝繧ｯ", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->CheckMedia(this);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	$58 - Lock drive
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Lock()
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);
	ASSERT(windrv);
	ASSERT(windrv->isValidUnit(unit));
	ASSERT(windrv->GetFilesystem());

#ifdef WINDRV_LOG
	Log(Log::Normal, "$58 %d Lock drive", unit);
#endif // WINDRV_LOG

	// Call file system
	DWORD nResult = windrv->GetFilesystem()->Lock(this);

	LockXM();

	// Result
	SetResult(nResult);

	UnlockXM();
}

//---------------------------------------------------------------------------
//
//	ResultWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetResult(DWORD result)
{
	ASSERT(this);
	ASSERT(a5 <= 0xFFFFFF);

	// 閾ｴ蜻ｽ逧Error蛻､螳
	DWORD fatal = 0;
	switch (result) {
	case FS_FATAL_INVALIDUNIT: fatal = 0x5001; break;
	case FS_FATAL_INVALIDCOMMAND: fatal = 0x5003; break;
	case FS_FATAL_WRITEPROTECT: fatal = 0x700D; break;
	case FS_FATAL_MEDIAOFFLINE: fatal = 0x7002; break;
	}

	// Calculate result
	if (fatal) {
		// Retry possible繧定ｿ斐☆縺ｨ縺阪ｯ縲(a5 + 18)繧呈嶌縺肴鋤縺医※縺ｯ縺縺代↑縺縲
		// 縺昴ｮ蠕檎區蟶ｯ縺ｧ Retry 繧帝∈謚槭＠縺溷ｴ蜷医∵嶌縺肴鋤縺医◆蛟､繧定ｪｭ縺ｿ霎ｼ繧薙〒隱､蜍穂ｽ懊＠縺ｦ縺励∪縺縲
		result = FS_INVALIDFUNC;
		SetByte(a5 + 3, fatal & 255);
		SetByte(a5 + 4, fatal >> 8);
		if ((fatal & 0x2000) == 0) {
			SetLong(a5 + 18, result);
		}
	} else {
		SetLong(a5 + 18, result);
	}

#if defined(WINDRV_LOG)
	// Error縺後↑縺代ｌ縺ｰEnd
	if (result < 0xFFFFFF80) return;

	// Error繝｡繝繧ｻ繝ｼ繧ｸ
	TCHAR* szError;
	switch (result) {
	case FS_INVALIDFUNC: szError = "Invalid縺ｪ繝輔ぃ繝ｳ繧ｯ繧ｷ繝ｧ繝ｳ繧ｳ繝ｼ繝峨ｒExecute後＠縺ｾ縺励◆"; break;
	case FS_FILENOTFND: szError = "謖螳壹＠縺溘ヵ繧｡繧､繝ｫ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ"; break;
	case FS_DIRNOTFND: szError = "謖螳壹＠縺溘ョ繧｣繝ｬ繧ｯ繝医Μ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ"; break;
	case FS_OVEROPENED: szError = "Open縺励※縺繧九ヵ繧｡繧､繝ｫ縺悟､壹☆縺弱∪縺"; break;
	case FS_CANTACCESS: szError = "繝繧｣繝ｬ繧ｯ繝医Μ繧繝懊Μ繝･繝ｼ繝繝ｩ繝吶Ν縺ｯ繧｢繧ｯ繧ｻ繧ｹ荳榊庄縺ｧ縺"; break;
	case FS_NOTOPENED: szError = "謖螳壹＠縺溘ワ繝ｳ繝峨Ν縺ｯOpen縺輔ｌ縺ｦ縺縺ｾ縺帙ｓ"; break;
	case FS_INVALIDMEM: szError = "繝｡繝｢繝ｪ邂｡逅鬆伜沺縺檎ｴ螢翫＆繧後∪縺励◆"; break;
	case FS_OUTOFMEM: szError = "Execute後↓蠢隕√↑繝｡繝｢繝ｪ縺後≠繧翫∪縺帙ｓ"; break;
	case FS_INVALIDPTR: szError = "Invalid縺ｪ繝｡繝｢繝ｪ邂｡逅繝昴う繝ｳ繧ｿ繧呈欠螳壹＠縺ｾ縺励◆"; break;
	case FS_INVALIDENV: szError = "荳肴ｭ｣縺ｪ迺ｰ蠅繧呈欠螳壹＠縺ｾ縺励◆"; break;
	case FS_ILLEGALFMT: szError = "Execute後ヵ繧｡繧､繝ｫ縺ｮ繝輔か繝ｼ繝槭ャ繝医′逡ｰ蟶ｸ縺ｧ縺"; break;
	case FS_ILLEGALMOD: szError = "Open縺ｮ繧｢繧ｯ繧ｻ繧ｹ繝｢繝ｼ繝峨′逡ｰ蟶ｸ縺ｧ縺"; break;
	case FS_INVALIDPATH: szError = "繝輔ぃ繧､繝ｫ蜷阪ｮ謖螳壹↓隱､繧翫′縺ゅｊ縺ｾ縺"; break;
	case FS_INVALIDPRM: szError = "Invalid縺ｪParameter縺ｧ繧ｳ繝ｼ繝ｫ縺励∪縺励◆"; break;
	case FS_INVALIDDRV: szError = "Drive specification is invalid"; break;
	case FS_DELCURDIR: szError = "繧ｫ繝ｬ繝ｳ繝医ョ繧｣繝ｬ繧ｯ繝医Μ縺ｯDelete縺ｧ縺阪∪縺帙ｓ"; break;
	case FS_NOTIOCTRL: szError = "IOCTRL縺ｧ縺阪↑縺繝繝舌う繧ｹ縺ｧ縺"; break;
	case FS_LASTFILE: szError = "縺薙ｌ莉･荳翫ヵ繧｡繧､繝ｫ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ"; break;
	case FS_CANTWRITE: szError = "謖螳壹ｮ繝輔ぃ繧､繝ｫ縺ｯWrite縺ｧ縺阪∪縺帙ｓ"; break;
	case FS_DIRALREADY: szError = "謖螳壹ｮ繝繧｣繝ｬ繧ｯ繝医Μ縺ｯ譌｢縺ｫ逋ｻ骭ｲ縺輔ｌ縺ｦ縺縺ｾ縺"; break;
	case FS_CANTDELETE: szError = "繝輔ぃ繧､繝ｫ縺後≠繧九ｮ縺ｧDelete縺ｧ縺阪∪縺帙ｓ"; break;
	case FS_CANTRENAME: szError = "繝輔ぃ繧､繝ｫ縺後≠繧九ｮ縺ｧ繝ｪ繝阪ｼ繝縺ｧ縺阪∪縺帙ｓ"; break;
	case FS_DISKFULL: szError = "繝繧｣繧ｹ繧ｯ縺御ｸ譚ｯ縺ｧ繝輔ぃ繧､繝ｫ縺御ｽ懊ｌ縺ｾ縺帙ｓ"; break;
	case FS_DIRFULL: szError = "繝繧｣繝ｬ繧ｯ繝医Μ縺御ｸ譚ｯ縺ｧ繝輔ぃ繧､繝ｫ縺御ｽ懊ｌ縺ｾ縺帙ｓ"; break;
	case FS_CANTSEEK: szError = "謖螳壹ｮ菴咲ｽｮ縺ｫ縺ｯSeek縺ｧ縺阪∪縺帙ｓ"; break;
	case FS_SUPERVISOR: szError = "繧ｹ繝ｼ繝代ｼ繝舌う繧ｶ迥ｶ諷九〒繧ｹ繝ｼ繝代ヰ繧､繧ｶ謖螳壹＠縺ｾ縺励◆"; break;
	case FS_THREADNAME: szError = "蜷後§繧ｹ繝ｬ繝繝牙錐縺悟ｭ伜惠縺励∪縺"; break;
	case FS_BUFWRITE: szError = "繝励Ο繧ｻ繧ｹ髢馴壻ｿ｡縺ｮ繝舌ャ繝輔ぃ縺梧嶌霎ｼ縺ｿ遖∵ｭ｢縺ｧ縺"; break;
	case FS_BACKGROUND: szError = "繝舌ャ繧ｯ繧ｰ繝ｩ繧ｦ繝ｳ繝峨励Ο繧ｻ繧ｹ繧定ｵｷ蜍輔〒縺阪∪縺帙ｓ"; break;
	case FS_OUTOFLOCK: szError = "繝ｭ繝繧ｯ鬆伜沺縺瑚ｶｳ繧翫∪縺帙ｓ"; break;
	case FS_LOCKED: szError = "繝ｭ繝繧ｯ縺輔ｌ縺ｦ縺縺ｦ繧｢繧ｯ繧ｻ繧ｹ縺ｧ縺阪∪縺帙ｓ"; break;
	case FS_DRIVEOPENED: szError = "謖螳壹ｮ繝峨Λ繧､繝悶ｯ繝上Φ繝峨Λ縺後が繝ｼ繝励Φ縺輔ｌ縺ｦ縺縺ｾ縺"; break;
	case FS_LINKOVER: szError = "繧ｷ繝ｳ繝懊Μ繝繧ｯ繝ｪ繝ｳ繧ｯ繝阪せ繝医′16蝗槭ｒ雜縺医∪縺励◆"; break;
	case FS_FILEEXIST: szError = "繝輔ぃ繧､繝ｫ縺悟ｭ伜惠縺励∪縺"; break;
	default: szError = "譛ｪ螳夂ｾｩ縺ｮError縺ｧ縺"; break;
	}
	switch (fatal & 255) {
	case 0: break;
	case 1: szError = "Invalid縺ｪUnit number繧呈欠螳壹＠縺ｾ縺励◆"; break;
	case 2: szError = "繝繧｣繧ｹ繧ｯ縺悟･縺｣縺ｦ縺縺ｾ縺帙ｓ"; break;
	case 3: szError = "Invalid縺ｪ繧ｳ繝槭Φ繝臥分蜿ｷ繧呈欠螳壹＠縺ｾ縺励◆"; break;
	case 4: szError = "CRCError縺檎匱逕溘＠縺ｾ縺励◆"; break;
	case 5: szError = "繝繧｣繧ｹ繧ｯ縺ｮ邂｡逅鬆伜沺縺檎ｴ螢翫＆繧後※縺縺ｾ縺"; break;
	case 6: szError = "Seek縺ｫ螟ｱ謨励＠縺ｾ縺励◆"; break;
	case 7: szError = "Invalid縺ｪ繝｡繝繧｣繧｢繧剃ｽｿ逕ｨ縺励∪縺励◆"; break;
	case 8: szError = "Sector not found"; break;
	case 9: szError = "繝励Μ繝ｳ繧ｿ縺後▽縺ｪ縺後▲縺ｦ縺縺ｾ縺帙ｓ"; break;
	case 10: szError = "WriteError縺檎匱逕溘＠縺ｾ縺励◆"; break;
	case 11: szError = "ReadError縺檎匱逕溘＠縺ｾ縺励◆"; break;
	case 12: szError = "縺昴ｮ莉悶ｮError縺檎匱逕溘＠縺ｾ縺励◆"; break;
	case 13: szError = "Write遖∵ｭ｢縺ｮ縺溘ａExecute後〒縺阪∪縺帙ｓ"; break;
	case 14: szError = "Write縺ｧ縺阪∪縺帙ｓ"; break;
	case 15: szError = "繝輔ぃ繧､繝ｫAttribute change阪′逋ｺ逕溘＠縺ｾ縺励◆"; break;
	default: szError = "譛ｪ螳夂ｾｩ縺ｮ閾ｴ蜻ｽ逧Error縺ｧ縺"; break;
	}

	Log(Log::Warning, "$%X %d %s(%d)", command, unit, szError, result);
#endif // WINDRV_LOG
}

//---------------------------------------------------------------------------
//
//	Device read
//
//---------------------------------------------------------------------------
DWORD FASTCALL CWindrv::GetByte(DWORD addr) const
{
	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);

	// 8bit
	return memory->ReadOnly(addr);
}

//---------------------------------------------------------------------------
//
//	Device write
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetByte(DWORD addr, DWORD data)
{
	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);
	ASSERT(data < 0x100);

	// 8bit
	memory->WriteByte(addr, data);
}

//---------------------------------------------------------------------------
//
//	Word read
//
//---------------------------------------------------------------------------
DWORD FASTCALL CWindrv::GetWord(DWORD addr) const
{
	DWORD data;

	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);

	// 16bit
	data = memory->ReadOnly(addr);
	data <<= 8;
	data |= memory->ReadOnly(addr + 1);

	return data;
}

//---------------------------------------------------------------------------
//
//	繝ｯ繝ｼ繝画嶌縺崎ｾｼ縺ｿ
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetWord(DWORD addr, DWORD data)
{
	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);
	ASSERT(data < 0x10000);

	// 16bit
	memory->WriteWord(addr, data);
}

//---------------------------------------------------------------------------
//
//	繝ｭ繝ｳ繧ｰRead
//
//---------------------------------------------------------------------------
DWORD FASTCALL CWindrv::GetLong(DWORD addr) const
{
	DWORD data;

	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);

	// 32bit
	data = memory->ReadOnly(addr);
	data <<= 8;
	data |= memory->ReadOnly(addr + 1);
	data <<= 8;
	data |= memory->ReadOnly(addr + 2);
	data <<= 8;
	data |= memory->ReadOnly(addr + 3);

	return data;
}

//---------------------------------------------------------------------------
//
//	繝ｭ繝ｳ繧ｰWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetLong(DWORD addr, DWORD data)
{
	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);

	// 32bit
	memory->WriteWord(addr, (WORD)(data >> 16));
	memory->WriteWord(addr + 2, (WORD)data);
}

//---------------------------------------------------------------------------
//
//	繧｢繝峨Ξ繧ｹRead
//
//---------------------------------------------------------------------------
DWORD FASTCALL CWindrv::GetAddr(DWORD addr) const
{
	DWORD data;

	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);

	// 24bit(譛蛻昴ｮ1繝舌う繝医ｯ辟｡隕)
	data = memory->ReadOnly(addr + 1);
	data <<= 8;
	data |= memory->ReadOnly(addr + 2);
	data <<= 8;
	data |= memory->ReadOnly(addr + 3);

	return data;
}

//---------------------------------------------------------------------------
//
//	繧｢繝峨Ξ繧ｹWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetAddr(DWORD addr, DWORD data)
{
	ASSERT(this);
	ASSERT(memory);
	ASSERT(addr <= 0xffffff);
	ASSERT(data <= 0xffffff);

	// 24bit(譛蛻昴ｮ1繝舌う繝医ｯ蠢縺0)
	data &= 0xffffff;
	memory->WriteWord(addr, (WORD)(data >> 16));
	memory->WriteWord(addr + 2, (WORD)data);
}

//---------------------------------------------------------------------------
//
//	NAMESTSPath崎ｪｭ縺ｿ霎ｼ縺ｿ
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetNameStsPath(DWORD addr, Human68k::namests_t *pNamests) const
{
	DWORD offset;

	ASSERT(this);
	ASSERT(pNamests);
	ASSERT(addr <= 0xFFFFFF);

	// Wildcard information
	pNamests->wildcard = (BYTE)GetByte(addr + 0);

	// Drive letter
	pNamests->drive = (BYTE)GetByte(addr + 1);

	// Path
	for (offset=0; offset<sizeof(pNamests->path); offset++) {
		pNamests->path[offset] = (BYTE)GetByte(addr + 2 + offset);
	}

	// 繝輔ぃ繧､繝ｫ蜷1
	memset(pNamests->name, 0x20, sizeof(pNamests->name));

	// Extension
	memset(pNamests->ext, 0x20, sizeof(pNamests->ext));

	// 繝輔ぃ繧､繝ｫ蜷2
	memset(pNamests->add, 0, sizeof(pNamests->add));

#if defined(WINDRV_LOG)
{
	TCHAR szPath[_MAX_PATH];
	pNamests->GetCopyPath((BYTE*)szPath);	// WARNING: Unicode譎りｦ∽ｿｮ豁｣

	Log(Log::Detail, "Path %s", szPath);
}
#endif // WINDRV_LOG
}

//---------------------------------------------------------------------------
//
//	NAMESTSRead
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetNameSts(DWORD addr, Human68k::namests_t *pNamests) const
{
	DWORD offset;

	ASSERT(this);
	ASSERT(pNamests);
	ASSERT(addr <= 0xFFFFFF);

	// Wildcard information
	pNamests->wildcard = (BYTE)GetByte(addr + 0);

	// Drive letter
	pNamests->drive = (BYTE)GetByte(addr + 1);

	// Path
	for (offset=0; offset<sizeof(pNamests->path); offset++) {
		pNamests->path[offset] = (BYTE)GetByte(addr + 2 + offset);
	}

	// 繝輔ぃ繧､繝ｫ蜷1
	for (offset=0; offset<sizeof(pNamests->name); offset++) {
		pNamests->name[offset] = (BYTE)GetByte(addr + 67 + offset);
	}

	// Extension
	for (offset=0; offset<sizeof(pNamests->ext); offset++) {
		pNamests->ext[offset] = (BYTE)GetByte(addr + 75 + offset);
	}

	// 繝輔ぃ繧､繝ｫ蜷2
	for (offset=0; offset<sizeof(pNamests->add); offset++) {
		pNamests->add[offset] = (BYTE)GetByte(addr + 78 + offset);
	}

#if defined(WINDRV_LOG)
{
	TCHAR szPath[_MAX_PATH];
	pNamests->GetCopyPath((BYTE*)szPath);	// WARNING: Unicode譎りｦ∽ｿｮ豁｣

	TCHAR szFilename[_MAX_PATH];
	pNamests->GetCopyFilename((BYTE*)szFilename);	// WARNING: Unicode譎りｦ∽ｿｮ豁｣

	if (pNamests->wildcard == 0xFF) {
		Log(Log::Detail, "Path %s", szPath);
	} else {
		Log(Log::Detail, "Filename %s%s", szPath, szFilename);
	}
}
#endif // WINDRV_LOG
}

//---------------------------------------------------------------------------
//
//	FILESRead
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetFiles(DWORD addr, Human68k::files_t* pFiles) const
{
	ASSERT(this);
	ASSERT(pFiles);
	ASSERT(addr <= 0xFFFFFF);

	// Search諠蝣ｱ
	pFiles->fatr = (BYTE)GetByte(addr + 0);		// Read only
	pFiles->drive = (BYTE)GetByte(addr + 1);	// Read only
	pFiles->sector = GetLong(addr + 2);
	//pFiles->sector2 = (WORD)GetWord(addr + 6);	// Read only
	pFiles->offset = (WORD)GetWord(addr + 8);

#if 0
	DWORD offset;

	// 繝輔ぃ繧､繝ｫ蜷
	for (offset=0; offset<sizeof(pFiles->name); offset++) {
		pFiles->name[offset] = (BYTE)GetByte(addr + 10 + offset);
	}

	// Extension
	for (offset=0; offset<sizeof(pFiles->ext); offset++) {
		pFiles->ext[offset] = (BYTE)GetByte(addr + 18 + offset);
	}
#endif

#if 0
	// 繝輔ぃ繧､繝ｫ諠蝣ｱ
	pFiles->attr = (BYTE)GetByte(addr + 21);
	pFiles->time = (WORD)GetWord(addr + 22);
	pFiles->date = (WORD)GetWord(addr + 24);
	pFiles->size = GetLong(addr + 26);

	// 繝輔Ν繝輔ぃ繧､繝ｫ蜷
	for (offset=0; offset<sizeof(pFiles->full); offset++) {
		pFiles->full[offset] = (BYTE)GetByte(addr + 30 + offset);
	}
#else
	pFiles->attr = 0;
	pFiles->time = 0;
	pFiles->date = 0;
	pFiles->size = 0;
	memset(pFiles->full, 0, sizeof(pFiles->full));
#endif
}

//---------------------------------------------------------------------------
//
//	FILESWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetFiles(DWORD addr, const Human68k::files_t* pFiles)
{
	DWORD offset;

	ASSERT(this);
	ASSERT(pFiles);
	ASSERT(addr <= 0xFFFFFF);

	SetLong(addr + 2, pFiles->sector);
	SetWord(addr + 8, pFiles->offset);

#if 0
	// Search諠蝣ｱ
	SetByte(addr + 0, pFiles->fatr);	// Read only
	SetByte(addr + 1, pFiles->drive);	// Read only
	SetWord(addr + 6, pFiles->sector2);	// Read only

	// 繝輔ぃ繧､繝ｫ蜷
	for (offset=0; offset<sizeof(pFiles->name); offset++) {
		SetByte(addr + 10 + offset, pFiles->name[offset]);
	}

	// Extension
	for (offset=0; offset<sizeof(pFiles->ext); offset++) {
		SetByte(addr + 18 + offset, pFiles->ext[offset]);
	}
#endif

	// 繝輔ぃ繧､繝ｫ諠蝣ｱ
	SetByte(addr + 21, pFiles->attr);
	SetWord(addr + 22, pFiles->time);
	SetWord(addr + 24, pFiles->date);
	SetLong(addr + 26, pFiles->size);

	// 繝輔Ν繝輔ぃ繧､繝ｫ蜷
	for (offset=0; offset<sizeof(pFiles->full); offset++) {
		SetByte(addr + 30 + offset, pFiles->full[offset]);
	}

#if defined(WINDRV_LOG)
{
	TCHAR szAttribute[16];
	BYTE nAttribute = pFiles->attr;
	for (int i = 0; i < 8; i++) {
		TCHAR c = '-';
		if ((nAttribute & 0x80) != 0)
			c = "XLADVSHR"[i];
		szAttribute[i] = c;
		nAttribute <<= 1;
	}
	szAttribute[8] = '\0';

	Log(Log::Detail, "%s %s %d", szAttribute, pFiles->full, pFiles->size);
}
#endif // WINDRV_LOG
}

//---------------------------------------------------------------------------
//
//	FCBRead
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetFcb(DWORD addr, Human68k::fcb_t* pFcb) const
{
	ASSERT(this);
	ASSERT(pFcb);
	ASSERT(addr <= 0xFFFFFF);

	// FCB諠蝣ｱ
	pFcb->fileptr = GetLong(addr + 6);
	pFcb->mode = (WORD)GetWord(addr + 14);
	//pFcb->zero = GetLong(addr + 32);

#if 0
	DWORD i;

	// 繝輔ぃ繧､繝ｫ蜷
	for (i = 0; i < sizeof(pFcb->name); i++) {
		pFcb->name[i] = (BYTE)GetByte(addr + 36 + i);
	}

	// Extension
	for (i = 0; i < sizeof(pFcb->ext); i++) {
		pFcb->ext[i] = (BYTE)GetByte(addr + 44 + i);
	}

	// 繝輔ぃ繧､繝ｫ蜷2
	for (i = 0; i < sizeof(pFcb->add); i++) {
		pFcb->add[i] = (BYTE)GetByte(addr + 48 + i);
	}
#endif

	// Attribute
	pFcb->attr = (BYTE)GetByte(addr + 47);

	// FCB諠蝣ｱ
	pFcb->time = (WORD)GetWord(addr + 58);
	pFcb->date = (WORD)GetWord(addr + 60);
	//pFcb->cluster = (WORD)GetWord(addr + 62);
	pFcb->size = GetLong(addr + 64);
}

//---------------------------------------------------------------------------
//
//	FCBWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetFcb(DWORD addr, const Human68k::fcb_t* pFcb)
{
	ASSERT(this);
	ASSERT(pFcb);
	ASSERT(addr <= 0xFFFFFF);

	// FCB諠蝣ｱ
	SetLong(addr + 6, pFcb->fileptr);
	SetWord(addr + 14, pFcb->mode);
	// SetLong(addr + 32, pFcb->zero);

#if 0
	DWORD i;

	// 繝輔ぃ繧､繝ｫ蜷
	for (i = 0; i < sizeof(pFcb->name); i++) {
		SetByte(addr + 36 + i, pFcb->name[i]);
	}

	// Extension
	for (i = 0; i < sizeof(pFcb->ext); i++) {
		SetByte(addr + 44 + i, pFcb->ext[i]);
	}

	// 繝輔ぃ繧､繝ｫ蜷2
	for (i = 0; i < sizeof(pFcb->add); i++) {
		SetByte(addr + 48 + i, pFcb->add[i]);
	}
#endif

	// Attribute
	SetByte(addr + 47, pFcb->attr);

	// FCB諠蝣ｱ
	SetWord(addr + 58, pFcb->time);
	SetWord(addr + 60, pFcb->date);
	//SetWord(addr + 62, pFcb->cluster);
	SetLong(addr + 64, pFcb->size);
}

//---------------------------------------------------------------------------
//
//	CAPACITYWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetCapacity(DWORD addr, const Human68k::capacity_t* pCapacity)
{
	ASSERT(this);
	ASSERT(pCapacity);
	ASSERT(addr <= 0xffffff);

#ifdef WINDRV_LOG
	Log(Log::Detail, "Free:%d Clusters:%d Sectors:%d Bytes:%d",
		pCapacity->free, pCapacity->clusters, pCapacity->sectors, pCapacity->bytes);
#endif // WINDRV_LOG

	SetWord(addr + 0, pCapacity->free);
	SetWord(addr + 2, pCapacity->clusters);
	SetWord(addr + 4, pCapacity->sectors);
	SetWord(addr + 6, pCapacity->bytes);
}

//---------------------------------------------------------------------------
//
//	DPBWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetDpb(DWORD addr, const Human68k::dpb_t* pDpb)
{
	ASSERT(this);
	ASSERT(pDpb);
	ASSERT(addr <= 0xFFFFFF);

	// DPB諠蝣ｱ
	SetWord(addr + 0, pDpb->sector_size);
	SetByte(addr + 2, pDpb->cluster_size);
	SetByte(addr + 3, pDpb->shift);
	SetWord(addr + 4, pDpb->fat_sector);
	SetByte(addr + 6, pDpb->fat_max);
	SetByte(addr + 7, pDpb->fat_size);
	SetWord(addr + 8, pDpb->file_max);
	SetWord(addr + 10, pDpb->data_sector);
	SetWord(addr + 12, pDpb->cluster_max);
	SetWord(addr + 14, pDpb->root_sector);
	SetByte(addr + 20, pDpb->media);
}

//---------------------------------------------------------------------------
//
//	IOCTRLRead
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetIoctrl(DWORD param, DWORD func, Human68k::ioctrl_t* pIoctrl)
{
	ASSERT(this);
	ASSERT(pIoctrl);

	switch (func) {
	case 2:
		// 繝｡繝繧｣繧｢蜀崎ｪ崎ｭ
		pIoctrl->param = param;
		return;

	case -2:
		// Option set
		ASSERT(param <= 0xFFFFFF);
		pIoctrl->param = GetLong(param);
		return;

#if 0
	case 0:
		// 繝｡繝繧｣繧｢ID縺ｮacquire
		return;

	case 1:
		// Human68kCompatible縺ｮ縺溘ａ縺ｮ繝繝溘ｼ
		return;

	case -1:
		// Current position
		return;

	case -3:
		// 繧ｪ繝励す繝ｧ繝ｳacquire
		return;
#endif
	}
}

//---------------------------------------------------------------------------
//
//	IOCTRLWrite
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::SetIoctrl(DWORD param, DWORD func, const Human68k::ioctrl_t* pIoctrl)
{
	ASSERT(this);
	ASSERT(pIoctrl);

	switch (func) {
	case 0:
		// 繝｡繝繧｣繧｢ID縺ｮacquire
		ASSERT(param <= 0xFFFFFF);
		SetWord(param, pIoctrl->media);
		return;

	case 1:
		// Human68kCompatible縺ｮ縺溘ａ縺ｮ繝繝溘ｼ
		ASSERT(param <= 0xFFFFFF);
		SetLong(param, pIoctrl->param);
		return;

	case -1:
		// Current position
		ASSERT(param <= 0xFFFFFF);
		{
			for (int i = 0; i < 8; i++) SetByte(param + i, pIoctrl->buffer[i]);
		}
		return;

	case -3:
		// 繧ｪ繝励す繝ｧ繝ｳacquire
		ASSERT(param <= 0xFFFFFF);
		SetLong(param, pIoctrl->param);
		return;

#if 0
	case 2:
		// 繝｡繝繧｣繧｢蜀崎ｪ崎ｭ
		return;

	case -2:
		// Option set
		return;
#endif
	}
}

//---------------------------------------------------------------------------
//
//	ParameterRead
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::GetParameter(DWORD addr, BYTE* pOption, DWORD nSize)
{
	ASSERT(this);
	ASSERT(addr <= 0xFFFFFF);
	ASSERT(pOption);

	DWORD nMode = 0;
	BYTE* p = pOption;
	for (DWORD i = 0; i < nSize - 2; i++) {
		BYTE c = (BYTE)GetByte(addr + i);
		*p++ = c;
		switch (nMode) {
		case 0:
			if (c == '\0') {
				return;
			}
			nMode = 1;
			break;
		case 1:
			if (c == '\0') nMode = 0;
			break;
		}
	}

	*p++ = '\0';
	*p++ = '\0';
}

#ifdef WINDRV_LOG
//---------------------------------------------------------------------------
//
//	Log output
//
//---------------------------------------------------------------------------
void FASTCALL CWindrv::Log(DWORD level, char* format, ...) const
{
	ASSERT(this);
	ASSERT(format);
	ASSERT(windrv);

	va_list args;
	va_start(args, format);
	char message[512];
	vsprintf(message, format, args);
	va_end(args);

	windrv->Log(level, message);
}

//---------------------------------------------------------------------------
//
//	Log output
//
//---------------------------------------------------------------------------
void FASTCALL Windrv::Log(DWORD level, char* message) const
{
	ASSERT(this);
	ASSERT(message);

	LOG((enum Log::loglevel)level, "%s", message);
}
#endif // WINDRV_LOG
